### ISSUE TITLE
feat: create reusable testimoni card

### ISSUE THREAD

**Issue by Dimas-oktavian17** [openyourmind-indo/OpenYourMind-1#13]
### Create a reusable component for this 

Approach:
- Grid: you can use grid for this component, set the grid column to be 3 and make sure responsive in mobile 
- Flex 

**Notes: 
- component should using props for data binding | resources/js/components/base/ButtonComponent.vue
- register component in global app.js
- make sure always use conventional commits feat, chore, fix or anything that relate**

- ![Image](https://github.com/openyourmind-indo/OpenYourMind-1/assets/92313885/49728f0e-c3a4-4f98-8697-6a2578e2596c)

**Comment by codeyzx** [comment]
@Dimas-oktavian17 ty mas udh dikerjain, maaf baru berprogress 🙏
